# Generated by Django 5.0.1 on 2024-01-22 18:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_card_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='informacao',
        ),
        migrations.AddField(
            model_name='card',
            name='continente_relacionado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.card'),
        ),
    ]
