# Generated by Django 5.0.1 on 2024-01-22 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_card_continente_relacionado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='continente_relacionado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.card'),
        ),
    ]
