# Generated by Django 5.0.1 on 2024-01-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_card_imagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='legenda',
            field=models.CharField(default='', max_length=250),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='card',
            name='descricao',
            field=models.TextField(),
        ),
    ]
