# Generated by Django 5.0.1 on 2024-01-24 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0014_paises_choque_cultural_paises_outono_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paises',
            name='historicos',
            field=models.BooleanField(default=False),
        ),
    ]
