# Generated by Django 5.0.1 on 2024-01-29 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_pontos_turisticos_iframe_google_maps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pontos_turisticos',
            name='iframe_google_maps',
        ),
        migrations.AddField(
            model_name='pontos_turisticos',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='pontos_turisticos',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
    ]
