# Generated by Django 5.0.1 on 2024-01-29 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_alter_cidades_pais_relacionado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontos_turisticos',
            name='cidade_relacionada',
            field=models.CharField(default='', max_length=250),
        ),
    ]
