# Generated by Django 5.0.1 on 2024-01-29 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0023_alter_pontos_turisticos_cidade_relacionada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pontos_turisticos',
            name='cidade_relacionada',
        ),
    ]
