# Generated by Django 5.0.1 on 2024-01-29 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_remove_pontos_turisticos_cidade_relacionada'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontos_turisticos',
            name='cidade_relacionada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='home.cidades'),
        ),
    ]
