# Generated by Django 5.0.1 on 2024-01-30 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0029_remove_pontos_turisticos_pais_relacionado_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pontos_turisticos',
            old_name='imagem',
            new_name='imagem1',
        ),
        migrations.AddField(
            model_name='pontos_turisticos',
            name='imagem2',
            field=models.ImageField(blank=True, upload_to='fotos_pontos-turisticos/%Y/%m/%d'),
        ),
    ]
