# Generated by Django 5.0.1 on 2024-01-31 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0031_pontos_turisticos_imagem3'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pontos_turisticos',
            name='descricao',
        ),
        migrations.AlterField(
            model_name='pontos_turisticos',
            name='legenda',
            field=models.TextField(),
        ),
    ]
