# Generated by Django 5.0.1 on 2024-02-27 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_paises_presente_na_home'),
        ('roteiros', '0002_alter_roteiro_dias_viagem'),
    ]

    operations = [
        migrations.AddField(
            model_name='roteiro',
            name='paises',
            field=models.ManyToManyField(to='home.paises'),
        ),
        migrations.DeleteModel(
            name='Viagem',
        ),
    ]
