# Generated by Django 5.0.1 on 2024-02-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0036_paises_presente_na_home'),
        ('roteiros', '0003_roteiro_paises_delete_viagem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roteiro',
            name='paises',
            field=models.ManyToManyField(blank=True, to='home.paises'),
        ),
    ]
