# Generated by Django 5.0.1 on 2024-02-27 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roteiros', '0004_alter_roteiro_paises'),
    ]

    operations = [
        migrations.RenameField(
            model_name='roteiro',
            old_name='paises',
            new_name='grupo_paises',
        ),
    ]
