# Generated by Django 5.0.1 on 2024-02-27 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roteiros', '0005_rename_paises_roteiro_grupo_paises'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='roteiro',
            name='grupo_paises',
        ),
        migrations.AddField(
            model_name='roteiro',
            name='grupo_paises',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
