# Generated by Django 5.0.1 on 2024-02-27 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roteiros', '0006_remove_roteiro_grupo_paises_roteiro_grupo_paises'),
    ]

    operations = [
        migrations.AlterField(
            model_name='roteiro',
            name='grupo_paises',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
