# Generated by Django 5.0.1 on 2024-01-15 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('imagem', models.CharField(max_length=200)),
                ('descricao', models.CharField(max_length=250)),
                ('informacao', models.TextField()),
            ],
        ),
    ]
