# Generated by Django 5.0.1 on 2024-01-23 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_card_continente_relacionado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='fotos/%Y/%m/%d/'),
        ),
    ]
