# Generated by Django 5.0.1 on 2024-01-23 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_continentes_paises_pontos_turisticos_delete_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='Topico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(choices=[('OS MAIS QUERIDINHOS', 'Os mais queridinhos'), ('PARA CURTIR O VERÃO', 'Para curtir o verão'), ('PARA CURTIR O INVERNO', 'Para curtir o inverno')], max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='continentes',
            name='imagem',
            field=models.ImageField(blank=True, upload_to='fotos-continentes/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='paises',
            name='topicos',
            field=models.ManyToManyField(related_name='paises', to='home.topico'),
        ),
    ]
