# Generated by Django 5.0.1 on 2024-01-23 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_topico_alter_continentes_imagem_paises_topicos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paises',
            name='topicos',
            field=models.ManyToManyField(blank=True, related_name='paises', to='home.topico'),
        ),
    ]
