# Generated by Django 5.0.1 on 2024-01-23 20:35

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_alter_paises_topicos'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paises',
            name='topicos',
        ),
        migrations.AddField(
            model_name='paises',
            name='topicos',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, max_length=200, verbose_name=[('OS MAIS QUERIDINHOS', 'Os mais queridinhos'), ('PARA CURTIR O VERÃO', 'Para curtir o verão'), ('PARA CURTIR O INVERNO', 'Para curtir o inverno')]),
        ),
    ]
