# Generated by Django 5.0.1 on 2024-01-23 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_paises_topicos_paises_topicos'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Topico',
        ),
        migrations.RemoveField(
            model_name='paises',
            name='topicos',
        ),
        migrations.AddField(
            model_name='paises',
            name='inverno',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paises',
            name='popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paises',
            name='verao',
            field=models.BooleanField(default=False),
        ),
    ]
