# Generated by Django 5.0.1 on 2024-01-29 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0017_remove_pontos_turisticos_iframe_google_maps_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontos_turisticos',
            name='latitude',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='pontos_turisticos',
            name='longitude',
            field=models.CharField(max_length=250),
        ),
    ]
