# Generated by Django 5.0.1 on 2024-01-29 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_remove_pontos_turisticos_pais_relacionado_cidades_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cidades',
            name='pais_relacionado',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='home.paises'),
        ),
        migrations.AlterField(
            model_name='pontos_turisticos',
            name='cidade_relacionada',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='home.cidades'),
        ),
    ]
