# Generated by Django 5.0.1 on 2024-01-29 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_pontos_turisticos_pais_relacionado_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pontos_turisticos',
            options={'verbose_name_plural': 'Pontos Turísticos'},
        ),
    ]
