# Generated by Django 5.0.1 on 2024-01-30 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0030_rename_imagem_pontos_turisticos_imagem1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontos_turisticos',
            name='imagem3',
            field=models.ImageField(blank=True, upload_to='fotos_pontos-turisticos/%Y/%m/%d'),
        ),
    ]
