# Generated by Django 5.0.1 on 2024-02-05 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0035_alter_pontos_turisticos_cidade_relacionada'),
    ]

    operations = [
        migrations.AddField(
            model_name='paises',
            name='presente_na_home',
            field=models.BooleanField(default=False),
        ),
    ]
